### ISSUE TITLE
Build on Jetson Nano failed.

### ISSUE THREAD

**Issue by beniroquai** [alliedvision/linux_nvidia_jetson#1]
We bought the Jetson Nano recently, installed the recent Nvidia Image on a fresh SD-card and try to install the allied-vision suite on the device. After executing the following line an error is produced as follows

`
~/Downloads/linux_nvidia_jetson-master$  ./build.sh work_dir nano all all
>> [i]...Running script for building Linux4Tegra setup...
>> [d]...dedicated for L4T: R32.2.1 and Jetson ...
>> [i]...Export variables for compiling...
>> [d]...ARCH=arm64...
>> [d]...CROSS_COMPILE=/home/bene/Downloads/linux_nvidia_jetson-master/work_dir/gcc/gcc-7.3.1-aarch64/bin/aarch64-linux-gnu-...
>> [d]...INSTALL_MOD_PATH=/home/bene/Downloads/linux_nvidia_jetson-master/work_dir/Linux_for_Tegra/rootfs...
>> [i]...Clean kernel sources...
sudo: time: command not found
>> [d]...Could not clean kernel sources...
>> Failed...
>> [i]...Script execution...
>> Failed...
`

Is there any way to debug this? We used the explanation given in this repository.

Thank you very much for your help!

**Comment by beniroquai** [comment]
I followed this [link](https://www.alliedvision.com/en/products/software/embedded-software-and-drivers/precompiled-kernel.html) which gives the proper precompiled binaries. This is not quiet clear from the documentation. 

Thanks!

**Comment by fklostermann** [comment]
Hi, thank you for your question.
This repository contains the kernel sources and helper scripts for cross-compiling the kernel on an x86-64 host. It is recommended to run the scripts with Ubuntu version 18.04. 
It seems that the tool "time" is not installed on your system. Please make sure the corresponding package is installed on your host in order to use these scripts.

As you already mentioned, you may of course use the precompiled binaries as an alternative.
We also provide a ready-to-flash SD card image including the Alvium CSI-2 driver for the Nano DevKit: [Link](https://www.alliedvision.com/en/products/software/embedded-software-and-drivers/precompiled-kernel-copy-1/sd-card-image.html )

Best regards,
Florian

**Comment by beniroquai** [comment]
Thanks! :)

Am Di., 18. Feb. 2020 um 14:07 Uhr schrieb fklostermann <
notifications@github.com>:
