### ISSUE TITLE
Deploy kernel image twice for xavier?

### ISSUE THREAD

**Issue by ranshalit** [alliedvision/linux_nvidia_jetson#4]
Hello,

In readme it seems that both step 5 and step 9 deploy kernel image into board.
Why does it done twice for xavier ? Isn't one time flashing for image good enough ?

> Create a tarball with the kernel image and modules., 
>5. Copy the tarball to the target board. On the target board, extract the tarball and run the included install script.
>9 .Xavier users: Set Xavier to Force USB Recovery Mode and run deploy.sh again with parameter flash-kernel to flash the kernel image to the board.

Thanks

**Comment by fklostermann** [comment]
Hi,
in case of the Xavier, it is necessary to flash both the kernel image and the device tree blob to the board. Unfortunately, these two steps cannot be combined.

The tarball that is copied to the Xavier board contains the kernel modules. The install script copies the kernel modules to /lib/modules so that the new kernel can find its corresponding modules.

All in all, 3 steps are necessary for the Xavier:
1. Installing the kernel modules (copying the tarball to the Xavier and running the install script)
2. Flashing the kernel image
3. Flashing the device tree

**Comment by ranshalit** [comment]
Hi,

Thank you for the answer.
The tarball also contains kernel image, so it confused me. (therefore it is actually being copied twice).
Anyway, from your answer I assume now that the tarball step is more relevant for library modules, than to kernel.

Thanks!

**Comment by fklostermann** [comment]
You are right, for the Xavier the tarball step is only relevant for the library modules.
The kernel image is also included in the tarball because for the TX2 the kernel image is installed by copying it to the rootfs (instead of being flashed from a host).
